declare const LCodeSelector: ({ woundType, location, setLocation, side, setSide, severity, setSeverity, setLCode, lCode, setLCodeMain, setPressureUlcer, lCodeServer, vluSide, vluLocation, type, stage, setStage }: {
    woundType: any;
    location: any;
    setLocation: any;
    side: any;
    setSide: any;
    severity: any;
    setSeverity: any;
    setLCode: any;
    lCode: any;
    setLCodeMain: any;
    setPressureUlcer: any;
    lCodeServer: any;
    vluSide: any;
    vluLocation: any;
    type: any;
    stage: any;
    setStage: any;
}) => JSX.Element;
export default LCodeSelector;
