declare const OpenIVRSummary: ({ five, selectedRecord, handleDialogClose, existingIvrData, patient, practitioner, setPractitioner, payors, setPayors, products, setProducts, iCode, setICode, lCode, setLCode, eCode, setECode, cdCode, setCDCode, cptCode, setCPTCode, cptCode2, setCPTCode2, cptWoundSize1, setCPTWoundSize1, cptWoundSize2, setCPTWoundSize2, cptWound, setCPTWound, admitted, setAdmitted, placeOfService, setPlaceOfService, handleSubmit, }: {
    five: any;
    selectedRecord: any;
    handleDialogClose: any;
    existingIvrData: any;
    patient: any;
    practitioner: any;
    setPractitioner: any;
    payors: any;
    setPayors: any;
    products: any;
    setProducts: any;
    iCode: any;
    setICode: any;
    lCode: any;
    setLCode: any;
    eCode: any;
    setECode: any;
    cdCode: any;
    setCDCode: any;
    cptCode: any;
    setCPTCode: any;
    cptCode2: any;
    setCPTCode2: any;
    cptWoundSize1: any;
    setCPTWoundSize1: any;
    cptWoundSize2: any;
    setCPTWoundSize2: any;
    cptWound: any;
    setCPTWound: any;
    admitted: any;
    setAdmitted: any;
    placeOfService: any;
    setPlaceOfService: any;
    handleSubmit: any;
}) => JSX.Element;
export default OpenIVRSummary;
