

export const CompanyNames = [
    "1199 National Benefit Fund",
    "Aarp",
    "Acclaim Inc.",
    "Ace Property And Casualty Insurance Company",
    "Acs Benefit SErvices, Inc.",
    "Administrative SErvices, Inc.",
    "Advantage By Bridgeway Health Solutions",
    "Advantage By Buckeye Community Health Plan",
    "Advantage By Managed Health SErvices",
    "Advantage By Superior Healthplan",
    "Aetna (Commercial Plans Only)",
    "Aetna Better Health (Ca)",
    "Aetna Better Health (Fl)",
    "Aetna Better Health (Il)",
    "Aetna Better Health (Ks)",
    "Aetna Better Health (Ky)",
    "Aetna Better Health (La)",
    "Aetna Better Health (Md)",
    "Aetna Better Health (Mi)",
    "Aetna Better Health (Nj)",
    "Aetna Better Health (Nv)",
    "Aetna Better Health (Oh)",
    "Aetna Better Health (Pa)",
    "Aetna Better Health (Tx) Chip",
    "Aetna Better Health (Tx)",
    "Aetna Better Health (Va)",
    "Aetna Better Health (Wv)",
    "Aetna Long Term Care",
    "Aetna Ohiorise - Ohio Medicaid Mce",
    "Aetna Retiree Medical Plan Administrator",
    "Aetna SEnior Supplemental",
    "Aflac - Dental",
    "Aflac - Medicare Supplemental",
    "Aflac",
    "Agewell NEw York (Web Credentials Required)",
    "Agia, Inc.",
    "Alameda Alliance For Health Plan (Web Credentials Required)",
    "Alan Sturm And Associates - Dental",
    "Albuquerque Public Schools",
    "Aliera Health Care",
    "All Savers Life Insurance",
    "Allegiance Benefit Plan Management Inc.",
    "Alliance Coal Health Plan",
    "Alliant Health Plans",
    "Allianz Life Insurance Company Of NEw York",
    "Allied Benefit Systems, Inc.",
    "Allina Health Aetna",
    "Allwell",
    "Alohacare",
    "Alternative Insurance Resources, Inc",
    "Altius Health Plans",
    "Altus Dental",
    "Ambetter NEw Hampshire Healthy Families",
    "Ambetter Of Arkansas",
    "Ambetter Of Illinois",
    "Ambetter Of Tennessee",
    "Ambetter Superior Health Plan (Tx)",
    "Ambetter",
    "Ameriben",
    "American Family Insurance Group",
    "American General Life And Accident",
    "American General Life Insurance Company",
    "American Health Advantage Of Florida",
    "American Health Advantage Of Mississippi",
    "American Health Advantage Of Missouri",
    "American Health Advantage Of Oklahoma",
    "American Health Advantage Of Tennessee",
    "American Health Advantage Of Tx",
    "American Health Advantage Of Utah",
    "American Healthcare Alliance",
    "American Income Life Insurance Company",
    "American Insurance Administrators",
    "American Medical SEcurity (Ams)",
    "American National Insurance",
    "American National Life Insurance Company Of Texas",
    "American NEtwork Insurance Medicare Supplement",
    "American Postal Workers Union (Apwu)",
    "American Republic Insurance Company (Aric)",
    "American Retirement Life Insurance Company - Medicare Supplement",
    "Americhoice - Community And State",
    "Americhoice Of NEw Jersey (Commercial)",
    "Americhoice Of NEw Jersey (Medicaid)",
    "Americo Financial Life & Annuity",
    "Amerigroup",
    "Amerihealth (De, Nj, PA) - Inst Submitters",
    "Amerihealth (De,Nj,Pa) - Professional Submitters Only",
    "Amerihealth Administrators",
    "Amerihealth Caritas Dc",
    "Amerihealth Caritas Delaware",
    "Amerihealth Caritas Florida",
    "Amerihealth Caritas Louisiana (Formerly Lacare)",
    "Amerihealth Caritas NEw Hampshire",
    "Amerihealth Caritas NExt Nc",
    "Amerihealth Caritas North Carolina",
    "Amerihealth Caritas Northwestern PA",
    "Amerihealth Caritas Ohio Medicaid Mce",
    "Amerihealth Caritas Pennsylvania",
    "Amerihealth Caritas Vip Care Plus",
    "Amerihealth NEw Jersey",
    "Amerihealth Northeast Pennsylvania",
    "Amerihealth Pennsylvania",
    "Amerihealth Vip Care",
    "Ameritas Group - Ameritas Life Insurance Company",
    "Ameritas Group - First Ameritas Of NEw York",
    "Ameritas Group - First Reliance Standard Life",
    "Ameritas Group - Reliance Standard Life",
    "Ameritas Group - Standard Insurance Of NEw York",
    "Ameritas Group - Standard Insurance",
    "Anthem Bc California Dental",
    "Anthem Bcbs - Ohio Medicaid Mce",
    "Anthem Bcbs Colorado Dental",
    "Anthem Bcbs Connecticut Dental",
    "Anthem Bcbs Ga Dental",
    "Anthem Bcbs Indiana Dental",
    "Anthem Bcbs Kentucky Dental",
    "Anthem Bcbs Maine Dental",
    "Anthem Bcbs Missouri Dental",
    "Anthem Bcbs NEvada Dental",
    "Anthem Bcbs NEw Hampshire Dental",
    "Anthem Bcbs Ohio Dental",
    "Anthem Bcbs Virginia Dental",
    "Anthem Bcbs Wisconsin Dental",
    "Anthem Health Keepers",
    "Anthem Vivity",
    "Arise Health Care",
    "Arise Health Plan Medicare SElect Policy",
    "Arizona Complete Care",
    "Arizona Physicians Ipa - Community And State",
    "Arkansas Total Care",
    "Armadacare",
    "Arnett Health Plan",
    "Aspire Health Plan",
    "Aspirus Medicare Advantage",
    "Asuris Northwest Health",
    "Atrio Health Plan",
    "Aultcare",
    "Automated Benefit SErvices",
    "Auxiant",
    "Avera Health Plans",
    "Avmed Health Plans",
    "Badgercare Plus",
    "Bankers Fidelity Life Insurance Company",
    "Bankers Life And Casualty",
    "Banner Aetna",
    "Banner University Family Care",
    "Baycare SElect Health Plans",
    "Bc Illinois Medicare Advantage",
    "Bc Montana Medicare Advantage",
    "Bc NEw Mexico Medicare Advantage",
    "Bc Oklahoma Medicare Advantage",
    "Bc Texas Medicare Advantage",
    "Bcbs Hi - Hawaii Medical SErvice Association Hmsa",
    "Bcbs La Medicare Advantage",
    "Bcbs Of Arizona Advantage",
    "Bcbs Texas Medicaid Star Chip",
    "Bcbs Texas Medicaid Star Kids",
    "Bcbs Western NEw York Medicaid",
    "Bcbsmn Blue Plus Medicaid Non - Emergency Transport",
    "Bcbsmn Blue Plus Medicaid",
    "Behavioral Health Systems, Inc",
    "Benebay",
    "Benefit Management Inc.",
    "Better Health Plans (Unison Health Plan)",
    "Better Health Plans Of Florida",
    "Bind",
    "Blue Advantage - Bcbs La",
    "Blue Benefit Administrators Of Mass",
    "Blue Cross Blue Shield Alabama - Institutional (Bcbs Al)",
    "Blue Cross Blue Shield Alabama - Professional (Bcbs Al)",
    "Blue Cross Blue Shield Arizona (Bcbs Az)",
    "Blue Cross Blue Shield Arkansas (Bcbs Ar)",
    "Blue Cross Blue Shield Colorado - Anthem (Bcbs Co)",
    "Blue Cross Blue Shield Connecticut - Anthem (Bcbs Ct)",
    "Blue Cross Blue Shield De (Highmark) - Prof & Inst Claim Submitters Only",
    "Blue Cross Blue Shield De (Highmark) - Prof Claim Submitters Only",
    "Blue Cross Blue Shield Dist. Of Columbia - Carefirst (Bcbs Dc)",
    "Blue Cross Blue Shield Florida (Bcbs Fl)",
    "Blue Cross Blue Shield Georgia - Anthem (Bcbs Ga)",
    "Blue Cross Blue Shield Illinois - Hcsc (Bcbs Il)",
    "Blue Cross Blue Shield Indiana - Anthem (Bcbs In)",
    "Blue Cross Blue Shield Iowa (Bcbs Ia)",
    "Blue Cross Blue Shield Kansas (Bcbs Ks)",
    "Blue Cross Blue Shield Kansas City (Bcbs Ks)",
    "Blue Cross Blue Shield Kentucky - Anthem (Bcbs Ky)",
    "Blue Cross Blue Shield Louisiana (Bcbs La)",
    "Blue Cross Blue Shield Maine - Anthem (Bcbs Me)",
    "Blue Cross Blue Shield Maryland - Carefirst (Bcbs MD)",
    "Blue Cross Blue Shield Massachusetts (Bcbs Ma)",
    "Blue Cross Blue Shield Michigan - Institutional (Bcbs Mi)",
    "Blue Cross Blue Shield Michigan - Professional (Bcbs Mi)",
    "Blue Cross Blue Shield Minnesota (Bcbs Mn)",
    "Blue Cross Blue Shield Mississippi (Bcbs Ms)",
    "Blue Cross Blue Shield Missouri - Anthem (Bcbs Mo)",
    "Blue Cross Blue Shield Montana - Hcsc (Bcbs Mt)",
    "Blue Cross Blue Shield NEbraska (Bcbs NE)",
    "Blue Cross Blue Shield NEvada - Anthem (Bcbs Nv)",
    "Blue Cross Blue Shield NEw Hampshire - Anthem (Bcbs Nh)",
    "Blue Cross Blue Shield NEw Jersey - Horizon (Bcbs Nj)",
    "Blue Cross Blue Shield NEw Mexico - Hcsc (Bcbs Nm)",
    "Blue Cross Blue Shield NEw York - Central (Bcbs Ny)",
    "Blue Cross Blue Shield NEw York - Empire Anthem (Bcbs Ny)",
    "Blue Cross Blue Shield NEw York - Excellus (Bcbs Ny)",
    "Blue Cross Blue Shield NEw York - Rochester (Bcbs Ny)",
    "Blue Cross Blue Shield NEw York - Utica (Bcbs Ny)",
    "Blue Cross Blue Shield North Carolina (Bcbs Nc)",
    "Blue Cross Blue Shield North Dakota (Bcbs Nd)",
    "Blue Cross Blue Shield Ohio - Anthem (Bcbs Oh)",
    "Blue Cross Blue Shield Oklahoma - Hcsc (Bcbs Ok)",
    "Blue Cross Blue Shield Oregon - Regence (Bcbs Or)",
    "Blue Cross Blue Shield PA - Highmark Inst Claim Submitter Only",
    "Blue Cross Blue Shield PA - Highmark Institutional Only",
    "Blue Cross Blue Shield PA - Highmark Professional",
    "Blue Cross Blue Shield Pennsylvania - Northeastern (Bcbs PA)",
    "Blue Cross Blue Shield Puerto Rico - Triple-S Salud (Bcbs Pr)",
    "Blue Cross Blue Shield Rhode Island (Bcbs Ri)",
    "Blue Cross Blue Shield South Carolina (Bcbs Sc)",
    "Blue Cross Blue Shield South Dakota (Bcbs Sd)",
    "Blue Cross Blue Shield Tennessee (Bcbs Tn)",
    "Blue Cross Blue Shield Texas - Hcsc (Bcbs Tx)",
    "Blue Cross Blue Shield Utah - Regence (Bcbs Ut)",
    "Blue Cross Blue Shield Vermont (Bcbs Vt)",
    "Blue Cross Blue Shield Virginia - Anthem (Bcbs Va)",
    "Blue Cross Blue Shield Western NEw York - (Bcbswny)",
    "Blue Cross Blue Shield Wisconsin - Anthem (Bcbs Wi)",
    "Blue Cross Blue Shield Wv - Highmark Institutional",
    "Blue Cross Blue Shield Wv - Highmark Professional",
    "Blue Cross Blue Shield Wyoming (Bcbs Wy)",
    "Blue Cross California - Anthem (Bc Ca)",
    "Blue Cross Community Centennial",
    "Blue Cross Community Options",
    "Blue Cross Idaho (Bc Id)",
    "Blue Cross Pennsylvania - Capital (Bcbs PA)",
    "Blue Cross Pennsylvania - Independence - Inst",
    "Blue Cross Pennsylvania - Independence - Professional",
    "Blue Cross Washington And Alaska - Premera (Bcwa, Bc Ak)",
    "Blue Medicare Advantage",
    "Blue Shield California (Bs Ca)",
    "Blue Shield Idaho - Regence (Bs Id)",
    "Blue Shield NEw York - Northeastern (Bs Ny)",
    "Blue Shield Washington - Regence (Bs Wa)",
    "Bluechoice Healthplan South Carolina Medicaid",
    "Bluecross Medicare Advantage",
    "Bmc Healthnet Plan",
    "Boon Group",
    "Boon-Chapman Benefit Admin",
    "Braven Health",
    "Bravo Health",
    "Bridgespan",
    "Bright Health Plan Medicare Advantage - Dos 1/1/2022 And After",
    "Bright Health Plan Medicare Advantage Dos 12/31/2021 And Before",
    "Bright Healthcare - Dos 1/1/2022 And After",
    "Bright Healthcare - Dos 12/31/2021 And Before",
    "Brokers National-Dental",
    "Cal-Viva",
    "California Children SErvices (Web Credentials Required)",
    "Caloptima",
    "Capital Administrators",
    "Capital District Physicians Health Plan (Cdphp)",
    "Capital Health Plan",
    "Caprock",
    "Care N’ Care",
    "Care1st Health Plan Arizona",
    "Care1st Of California (Web Credentials Required)",
    "Carefirst Administrators",
    "Carefirst Medicare Advantage",
    "Carelon Behavioral Health",
    "Caremore",
    "Carepartners Of Connecticut",
    "Careplus Health Plan",
    "Caresource Arkansas",
    "Caresource Georgia",
    "Caresource Health",
    "Caresource Indiana",
    "Caresource Michigan Medicaid",
    "Caresource North Carolina",
    "Caresource Ohio Medicaid Mce",
    "Caresource Ohio",
    "Caresource West Virginia",
    "Carolina Care Plan, Inc. (Ccp)",
    "Carolina Complete Health",
    "Carpenters Health And Welfare Trust Fund Of St Louis",
    "Cds Group Health",
    "Celtic Insurance",
    "Cencal",
    "Cenpatico - Arizona",
    "Cenpatico - Florida",
    "Cenpatico - Georgia",
    "Cenpatico - Illinois",
    "Cenpatico - Indiana",
    "Cenpatico - Kansas",
    "Cenpatico - Kentucky",
    "Cenpatico - Massachusetts",
    "Cenpatico - Mississippi",
    "Cenpatico - Missouri",
    "Cenpatico - NEw Hampshire",
    "Cenpatico - Ohio",
    "Cenpatico - South Carolina",
    "Cenpatico - Texas",
    "Cenpatico - Wisconsin",
    "Cenpatico Behavioral Health Texas",
    "Cenpatico Behavioral Health",
    "Centene - Absolute Total Care",
    "Centene - Advantage By Peach State",
    "Centene - Advantage By Sunshine State",
    "Centene - Ambetter Sunshine Health",
    "Centene - Ascension Complete",
    "Centene - Bridgeway Arizona",
    "Centene - Buckeye Community Health",
    "Centene - California Health And Wellness",
    "Centene - Celticare",
    "Centene - Granite State Health Plan",
    "Centene - Home State Health Plan",
    "Centene - Kentucky Spirit Health Plan",
    "Centene - Louisiana Healthcare Connections",
    "Centene - Managed Health SErvices Indiana",
    "Centene - Managed Health SErvices Wisconsin",
    "Centene - Michigan Fidelis SEcure Care",
    "Centene - NEw Hampshire Healthy Families",
    "Centene - Ohio Medicaid Mce",
    "Centene - Peach State Health Plan",
    "Centene - Sunflower State Health (Kansas)",
    "Centene - Sunshine State Health Plan",
    "Centene - Superior Healthplan Texas",
    "Centene - Total Care Carolina",
    "Centene Advantage Plans",
    "Centivo",
    "Central Ca Alliance For Health",
    "Central Health Medicare Plan (Web Credentials Required)",
    "Central Reserve Life Ins Co. Medicare Supplement",
    "Central States Fund",
    "Central States Health & Life Co. Of Omaha",
    "Central States Indemnity",
    "Cerner Health Plan",
    "Champva/Spina Bifida/Children Of Women Vietnam Vets",
    "Children√Ïs Mercy PCn",
    "Christian Brothers SErvices",
    "Christie Student Health Plans",
    "Christus Health Plan Medicaid",
    "Christus Health Plan Nm Medicare Advantage",
    "Christus Health Plan Tx Hix",
    "Cigna",
    "Claims Management SErvice Inc.",
    "Clear Health Alliance",
    "Clover Health",
    "Cmfg Life Insurance",
    "Coastal Management SErvices-Aspire (Web Credentials Required)",
    "Colonial Penn Life",
    "Colorado Access",
    "Colorado Community Health Alliance",
    "Common Ground",
    "Commonwealth Care Alliance (Cca)",
    "Community Care Of Oklahoma",
    "Community Health Choice",
    "Community Health Group (Chg)",
    "Community Health Plan Of Washington (Chpw)",
    "Community Health Plan",
    "Community Healthfirst Medicare Advantage",
    "Concentrix Insurance Solutions",
    "Connecticare - Medicare",
    "Connecticare",
    "Consolidated Associates Railroad",
    "Consolidated Health Plan (Web Credentials Required)",
    "Constellation Health",
    "Consumers Life",
    "Consumers Mutual Insurance Of Michigan",
    "Continental General Insurance Company - Medicare Supplement",
    "Continental Life Insurance Company Of Brentwood, Tennessee",
    "Cook Childrens Health Plan",
    "Cook Medical Group",
    "Cooperative Benefit Administrators (Cba)",
    "Coordinated Care",
    "Coresource (Fmh)",
    "Coresource (Little Rock)",
    "Coresource (Md, PA, Il, Nc,In, Az, Mn)",
    "Coresource (Ohio)",
    "Country Life Insurance Company",
    "Countycare",
    "Covenant Administrators (Tpa)",
    "Coventry Health Care Of Florida",
    "Cox Health Plan",
    "Crum & Forster",
    "Csi Life Insurance Company",
    "Culinary Health Fund Unite Here Health",
    "Dean Health Plan",
    "Decare Dental Health Insurance",
    "Delta Dental Insurance Company - Alabama",
    "Delta Dental Insurance Company - Florida",
    "Delta Dental Insurance Company - Georgia",
    "Delta Dental Insurance Company - Louisiana",
    "Delta Dental Insurance Company - Mississippi",
    "Delta Dental Insurance Company - Montana",
    "Delta Dental Insurance Company - NEvada",
    "Delta Dental Insurance Company - Oklahoma",
    "Delta Dental Insurance Company - Texas",
    "Delta Dental Insurance Company - Utah",
    "Delta Dental Of Arizona",
    "Delta Dental Of California",
    "Delta Dental Of Colorado",
    "Delta Dental Of Connecticut",
    "Delta Dental Of Delaware",
    "Delta Dental Of Hawaii",
    "Delta Dental Of Illinois",
    "Delta Dental Of Iowa",
    "Delta Dental Of Maryland",
    "Delta Dental Of Michigan",
    "Delta Dental Of Minnesota",
    "Delta Dental Of Missouri",
    "Delta Dental Of NEbraska",
    "Delta Dental Of NEw Jersey",
    "Delta Dental Of NEw York",
    "Delta Dental Of North Dakota",
    "Delta Dental Of Pennsylvania",
    "Delta Dental Of Rhode Island",
    "Delta Dental Of Virginia",
    "Delta Dental Of Washington Dc",
    "Delta Dental Of Washington State",
    "Delta Dental Of West Virginia",
    "Deltacare USa - Claims",
    "Deltacare USa - Encounters",
    "Dental Benefit Providers",
    "Dentaquest",
    "Denver Health Medical Plan",
    "Deseret Mutual (Dmba)",
    "Devoted Health",
    "Director√Ïs Guild",
    "District No. 9, I. A. Of M. & A. W. Welfare Trust",
    "Diversified Administration Corp",
    "Doctors Healthcare Plans",
    "Driscoll Health Plan",
    "Easy Choice Health Plan California",
    "Ebms (Employee Benefit Management SErvices, Inc.)",
    "Educators Mutual Insurance (Emi)",
    "Elderplan",
    "Elips Life Insurance Company",
    "Emblem Health (Ghi Hmo, Ghi Ppo, Hip, Vytra)",
    "Empire Bc NEw York Dental",
    "Employee Benefit SErvices - Dental",
    "Empower Arkansas",
    "Entrust",
    "Epsi, Inc.",
    "Erie Family Life Insurance Company",
    "Essence Healthcare",
    "Evercare",
    "Everence Financial",
    "Everest Reinsurance Company",
    "Evergreen Health Co-Op",
    "Evergreen Health",
    "Everpointe",
    "Evry Health",
    "Exclusicare",
    "Fallon Community Health Plan",
    "Farm Bureau Health Plans",
    "Federated Insurance",
    "Fidelis Care NEw York",
    "First Carolina Care",
    "First Choice Health NEtwork",
    "First Choice Vip Care Plus",
    "First Medical NEtwork",
    "First United American Insurance Company",
    "Firstcare",
    "Fiserv Wausau",
    "Flex Compensation - Dental",
    "Florida Blue Medicare",
    "Florida Combined Life - Dental",
    "Florida Health Care Plans",
    "Food Employers & Bakery",
    "Freedom Health Medicare Advantage",
    "Friday Health Plan",
    "Fsl Admin By Kba",
    "G.m.p. Employers Retiree Trust",
    "Gateway Health Plan",
    "Geha - Government Employees Hospital Association",
    "Geisinger Health Plan Gold",
    "Geisinger Health Plan",
    "Gemcare",
    "Genworth Life And Annuity Insurance",
    "Genworth Life Insurance Company",
    "Gilsbar",
    "Global Health Inc",
    "Globe Life & Accident Insurance Company",
    "Gold Coast Health Plan (Web Credentials Required)",
    "Gold Kidney Health Plan",
    "Golden Rule",
    "Golden West Dental",
    "Great American Life Insurance Company Medicare Supplement",
    "Great Southern Life Insurance Company",
    "Group And Pension Administrators",
    "Group Dental SErvice",
    "Group Health Northwest",
    "Group Hospitalization And Medical SErvices",
    "Group Practice Affiliates",
    "Guardian Life Insurance Company Of America - Dental",
    "Harmony Health Plan",
    "Harvard Pilgrim Health Care",
    "Hawaii Mainland Admin (Hma)",
    "Hawaii Medical Assurance Association",
    "Health Alliance Medical Plan (Il)",
    "Health Alliance Medical Plans (Hap)",
    "Health Choice Arizona",
    "Health Choice Oklahoma",
    "Health First Health Plan",
    "Health First Insurance",
    "Health NEt National",
    "Health NEw England",
    "Health PArtners Pennsylvania",
    "Health Plan Of San Mateo",
    "Health Plan Of Upper Ohio Valley",
    "Health SErvices For Children With Special NEeds",
    "Health Share Of Oregon (Care Oregon)",
    "Health Tradition",
    "Healthcare Highways",
    "Healthcare Management Administrators",
    "Healthchoice SElect",
    "Healthcomp Administrators",
    "Healthe Exchange",
    "Healthease Kids",
    "Healthease",
    "Healthfirst NEw York",
    "Healthfirst Of NEw Jersey",
    "Healthgram (Primary Physicianscare)",
    "Healthnow",
    "Healthpartners Mn",
    "Healthplan Of NEvada",
    "Healthplans Inc.",
    "Healthplus Of Michigan",
    "Healthscope (Morris Assoc, Central Benefits, Employers Health, Plan Handlers)",
    "Healthscope Benefits Inc.",
    "Healthscope Hsb",
    "Healthsmart Benefit Solutions (Wells Fargo Tpa)",
    "Healthsmart Benefit Solutions",
    "Healthsource Provident - Dental",
    "Healthspring",
    "Healthteam Advantage",
    "Healthy Blue Dual Advantage Louisiana",
    "Healthy Blue Louisiana",
    "Healthy Blue Missouri",
    "Healthy Blue NEbraska",
    "Healthy Blue North Carolina",
    "Healthy Blue South Carolina",
    "Hennepin Health - Metropolitan Health Plan (Mhp)",
    "Hershey Healthsmile - Dental",
    "Highmark SEnior Solutions Company",
    "Hipny",
    "Hm Care Advantage Admin By Kba",
    "Hometown Health",
    "Hooray Health",
    "Horizon NEw Jersey Health",
    "Hsbs Oklahoma City",
    "Hudson Health Plan",
    "Humana - Health Horizons (Ohio Medicaid Mce)",
    "Humana Caresource (Ky)",
    "Humana Long Term Care",
    "Humana",
    "Icare (Independent Care Health Plan)",
    "Illinicare Health Plan",
    "Independence Administrators",
    "Independent Health",
    "Indiana University Health Plan (Medicare)",
    "Indiana University Health Plans (Commercial)",
    "Inland Empire Health",
    "Innovation Health",
    "Insurers Administrative Corporation (Iac)",
    "Integra Administrative Group",
    "Integrated Mental Health SErvices",
    "Iowa Total Care",
    "Jai Medical Systems",
    "Johns Hopkins Advantage MD",
    "Johns Hopkins Employee Health Plan",
    "Johns Hopkins Health Plan",
    "Johns Hopkins Healthcare LLC",
    "Johns Hopkins US Family Health Plan",
    "Kaiser Foundation Health Plan Of Colorado",
    "Kaiser Foundation Health Plan Of Hawaii",
    "Kaiser Foundation Health Plan Of The Mid-Atlantic",
    "Kaiser Foundation Health Plan Of The Northwest",
    "Kaiser Foundation Health Plan Of Washington",
    "Kaiser Foundation Ohio",
    "Kaiser Permanente Kpic",
    "Kaiser Permanente Of Georgia",
    "Kaiser Permanente Of Northern Ca",
    "Kaiser Permanente Of Southern Ca",
    "Kelsey-Seybold",
    "Kemper Benefits",
    "Kentucky PAssport (Formerly PAssport Health Plan)",
    "Key Benefit Administrators (In)",
    "Key Benefit Administrators",
    "Key Healthy PArtners",
    "Keysolution",
    "Keystone First Community Health Plan",
    "Keystone Mercy Health",
    "Keystone Vip Care",
    "Kitsap Physician SErvices",
    "Kskj Life",
    "L.a. Care Health Plan",
    "Lasso Healthcare Msa",
    "Leon Medical Centers Health Plan",
    "Liberty National Life Insurance Company",
    "Lifecare Assurance Company",
    "Lifewise Arizona",
    "Lifewise Assurance Company",
    "Lifewise Plan Of Oregon",
    "Lifewise Plan Of Washington",
    "Lighthouse Health Plan",
    "Lincoln Financial",
    "Lincoln Heritage",
    "Local 1199",
    "Lonestar Tpa",
    "Loomis Company",
    "Louisiana Health Exchange",
    "Loyal American Life Insurance Company - Medicare Supplement",
    "Loyal Christian Benefit Association",
    "Lucent Health",
    "Lumico Life Insurance",
    "Magellan Behavioral Health",
    "Magellan Complete Care Of Virginia",
    "Magellan Health Care",
    "Magnacare",
    "Magnolia Health Plan",
    "Maine Community Health Options",
    "Managed Care Of America",
    "Managed Care Of North America",
    "Managed Care Systems - (Web Credentials Required)",
    "Managed Health NEtwork (Mhn)",
    "Mapfre Life Puerto Rico",
    "March Vision Care",
    "Maricopa Care Advantage (Arizona)",
    "Martins Point Health Care",
    "Mary Washington Medicare Advantage",
    "Maryland Physicians Care",
    "Mass General Brigham Health Plan (Fka: Allways Health PArtners)",
    "Mclaren Health Care",
    "Mdwise Medicaid Health Plans",
    "Med-Pay Inc",
    "Medben",
    "Medcost Benefit SErvices",
    "Medica Government Programs",
    "Medica Health Care Plan - Florida",
    "Medica Health Plan Solutions",
    "Medica Health Plans (Medicare Advantage Lob)",
    "Medica",
    "Medica2 - Group/Policy Is: Ifb Individual Family Benefits",
    "Medicaid Alabama (Al)",
    "Medicaid Alaska (Ak)",
    "Medicaid Arizona - Ahcccs (Az)",
    "Medicaid Arkansas (Ar)",
    "Medicaid California - Medi-Cal (Ca)",
    "Medicaid Colorado (Co)",
    "Medicaid Connecticut (Ct)",
    "Medicaid Delaware (De)",
    "Medicaid District Of Columbia (Dc)",
    "Medicaid Florida (Fl)",
    "Medicaid Georgia (Ga)",
    "Medicaid Hawaii (Hi)",
    "Medicaid Idaho (Id)",
    "Medicaid Illinois (Il)",
    "Medicaid Indiana (In)",
    "Medicaid Iowa (Ia)",
    "Medicaid Kansas (Ks)",
    "Medicaid Kentucky (Ky)",
    "Medicaid Louisiana (La)",
    "Medicaid Maine (Me)",
    "Medicaid Maryland (Md)",
    "Medicaid Massachusetts (Ma)",
    "Medicaid Michigan (Mi) Pending Eligibility",
    "Medicaid Michigan (Mi)",
    "Medicaid Michigan - Michigan Michild (Mi)",
    "Medicaid Minnesota (Mn)",
    "Medicaid Mississippi (Ms)",
    "Medicaid Mississippi - Chip (Ms)",
    "Medicaid Missouri (Mo)",
    "Medicaid Montana (Mt)",
    "Medicaid NEbraska (Ne)",
    "Medicaid NEvada (Nv)",
    "Medicaid NEw Hampshire (Nh)",
    "Medicaid NEw Jersey (Nj)",
    "Medicaid NEw Mexico (Nm)",
    "Medicaid NEw York (Ny)",
    "Medicaid North Carolina (Nc)",
    "Medicaid North Dakota (Nd)",
    "Medicaid Ohio (Oh)",
    "Medicaid Oklahoma (Ok)",
    "Medicaid Oregon (Or)",
    "Medicaid Pennsylvania (Pa)",
    "Medicaid Rhode Island (Ri) (Web Credentials Required)",
    "Medicaid South Carolina (Sc)",
    "Medicaid South Dakota (Sd)",
    "Medicaid Tennessee (Tn)",
    "Medicaid Texas Acute (Tx)",
    "Medicaid Texas Ltc (Tx)",
    "Medicaid Utah (Ut)",
    "Medicaid Vermont",
    "Medicaid Virginia (Va)",
    "Medicaid Washington (Wa)",
    "Medicaid West Virginia (Wv)",
    "Medicaid Wisconsin (Wi)",
    "Medicaid Wisconsin - Chronic Disease Program (Wi)",
    "Medicaid Wisconsin - Well Woman Program (Wi)",
    "Medicaid Wyoming (Wy)",
    "Medical Associates Health Plan/Health Choices",
    "Medical Card System",
    "Medical Mutual Of Ohio",
    "Medicare - All States",
    "Medicare - Dsh Submitters",
    "Medicare Advantage - Pennsylvania",
    "Medicare Y Mucho Mas (Inmediata Health Group)",
    "Medico Insurance Company",
    "Medigold Health Plans",
    "Medstar Family Choice",
    "Medstar Health Plan",
    "Mercy Care Plan (Arizona)",
    "Meridian Health Plan Il Medicaid",
    "Meridian Health Plan Illinois Complete",
    "Meridian Health Plan Michigan Complete",
    "Meridian Health Plan Of Il",
    "Meritain Health",
    "Metlife Dental Family",
    "Metroplus Health Plan",
    "Metropolitan Property And Casualty Insurance Company",
    "Michael Reese",
    "Michigan Complete Health",
    "Mississippi State Employees And Teachers Health Plan",
    "Missouri (Mo) Health Plan (Community & State)",
    "Missouri Care",
    "Moda Health",
    "Molina - Ohio Medicaid Mce",
    "Molina Complete Care Of Virginia",
    "Molina Healthcare Of California",
    "Molina Healthcare Of Florida",
    "Molina Healthcare Of Idaho",
    "Molina Healthcare Of Illinois",
    "Molina Healthcare Of Iowa",
    "Molina Healthcare Of Michigan",
    "Molina Healthcare Of Mississippi Marketplace",
    "Molina Healthcare Of Mississippi",
    "Molina Healthcare Of Missouri",
    "Molina Healthcare Of NEvada",
    "Molina Healthcare Of NEw Mexico",
    "Molina Healthcare Of NEw York",
    "Molina Healthcare Of Ohio",
    "Molina Healthcare Of South Carolina",
    "Molina Healthcare Of Texas",
    "Molina Healthcare Of Utah",
    "Molina Healthcare Of Washington",
    "Molina Healthcare Of Wisconsin",
    "Monitor Life Insurance Company Of Ny",
    "Montefiore Cmo",
    "Municipal Health Benefit Fund",
    "Mutual Health SErvices",
    "Mutual Of Omaha Medicare Advantage",
    "Mutual Of Omaha",
    "Mvp Health Care (New York)",
    "National Association Of Letter Carriers (Nalc)",
    "National Telecommunications Cooperative Association (Ntca)",
    "Nebraska Total Care",
    "Neighborhood Health PArtnership",
    "Neighborhood Health Plan (Ri)",
    "Network Health Insurance Corp",
    "Network Health Plan Of Wi",
    "New Era Life Insurance Company",
    "Nextblue",
    "Northwest Administrators",
    "Nova Healthcare Administrators",
    "Novasys Health",
    "Ochsner Health Plan",
    "Ohana",
    "Oklahoma Employees Group Insurance Division",
    "Old Surety Life Insurance",
    "Operation Engineers Local No. 428 Health And Welfare",
    "Optima/Sentara",
    "Optumcare - Az, Ut",
    "Optumhealth Behavioral Solutions",
    "Oscar",
    "Oxford Health Plans",
    "Pacific Source Health Plan",
    "Pacificare Arizona",
    "Pacificare Oklahoma",
    "Pacificare Washington",
    "Pacificsource Administrators",
    "Pacificsource Community Solutions (Medicaid)",
    "Pacificsource Medicare",
    "Pan-American Life Insurance Company",
    "Pan-American Life Puerto Rico (Palic)",
    "Paramount Health",
    "Parkland Community Health Plan",
    "Partners National Health Plans Of Nc",
    "Partnership Health Plan Of California",
    "Passport Advantage",
    "Patriot Dental",
    "Payer Name",
    "Peak Health",
    "Peak Medicare Advantage",
    "Pekin Life Insurance",
    "Penn Treaty NEtwork America Insurance Medicare Supplement",
    "Pennsylvania Health And Wellness",
    "People First",
    "Peoples Health NEtwork",
    "Performcare",
    "Personal Insurance Administrators (Pia)",
    "Physicians Health Plan Northern In (Phpni)",
    "Physicians Health Plan Of Michigan",
    "Physicians Mutual Insurance Company",
    "Pinnacle Claims Management",
    "Pittman And Associates",
    "Plan De Salud Hospital Menonita",
    "Planned Administrator Inc.",
    "Prairie States",
    "Preferred Care PArtners Florida",
    "Preferred Medicare Choice (Inmediata Health Group Corp)",
    "Preferredone",
    "Premier Health",
    "Presbyterian Health Plan (Web Credentials Required)",
    "Prestige Health Choice",
    "Primewest Health",
    "Principal Financial Group (Nippon Life)",
    "Priority Health",
    "Professional Benefit Administrators Inc. (Oak Brook Il)",
    "Prominence Health Plan (Ppo And Hmo)",
    "Prominence Health Plan Of Texas (Medicare Advantage)",
    "Providence Health Plan",
    "Provident American Life And Health Insurance Co - Medicare Supplement",
    "Provident Preferred NEtwork - Dental",
    "Public Employee Benefit Authority",
    "Public Employees Health Program - Chip",
    "Public Employees Health Program - Medicare",
    "Public Employees Health Program",
    "Puritan Life Insurance",
    "Qualcare",
    "Qualchoice Arkansas",
    "Quartz Aso",
    "Quiktrip Corporation",
    "Regence Group Administrators",
    "Reserve National Insurance Company",
    "Riverlink Health (Web Credentials Required)",
    "Rocky Mountain Health Plan",
    "Royal NEighbors Of America",
    "S And S Healthcare Strategies",
    "S. USa Life Insurance Company, Inc.",
    "Samaritan Health Plans",
    "San Francisco Health Plan",
    "San Joaquin Health Plan",
    "Sana Benefits",
    "Sanford Health Plan",
    "Santa Clara Family Health Plan",
    "Sbli USa Life Insurance Company, Inc.",
    "Scan - SEnior Care Action NEtwork (Hmo)",
    "Schaller Anderson Aetna Better Health Of NEw York",
    "Schaller Anderson Aetna Better Health Oh",
    "Schaller Anderson Aetna Illinois Medicaid",
    "Schaller Anderson Integral Quality Care Florida",
    "Schaller Anderson Majestacare Virginia",
    "Schaller Anderson Maryland Physicians Care",
    "Schaller Anderson Mercy Care",
    "Schaller Anderson Mercy Maricopa",
    "Schaller Anderson Missouri Care",
    "Schaller Anderson Texas Christus",
    "Scion Dental",
    "Scott And White Health Plan",
    "Securian Dental",
    "Securian/Patriot Dental",
    "Security Health Plan",
    "Select Health Of South Carolina",
    "Select Health Utah",
    "Selman & Company",
    "Selman Tricare",
    "Senior Dimensions",
    "Senior Health SErvices Center - Univ American Family Company",
    "Senior Whole Health NEw York",
    "Senior Whole Health Of Massachusetts",
    "Senior Whole Health",
    "Seniorcare - Wi",
    "Sentinel SEcurity Life Insurance Company",
    "Shared Health Mississippi",
    "Sharp Health Plan",
    "Shenandoah Life Insurance",
    "Sierra Health SErvices",
    "Significa Benefit SErvices",
    "Silversummit",
    "Simply Healthcare - Long Term Care",
    "Simply Healthcare Plans",
    "Simpra Advantage",
    "Sisco Benefits",
    "Soundpath Health",
    "South Country Health Alliance Medicaid",
    "South Country Health Alliance Medicare",
    "Special Agents Mutual Benefit Association",
    "Spectera United Healthcare Vision",
    "Spectrum Health",
    "Spjst - Medicare Supplement",
    "Standard Life And Accident Insurance Company",
    "Star Hrg",
    "State Farm",
    "State Mutual (Lincoln Novation)",
    "State Mutual Med Supplement",
    "Staywell Kids",
    "Staywell",
    "Stewart C Miller And Company",
    "Summacare Health Plan",
    "Summit America Insurance SErvices, Inc.",
    "Summit Community Care",
    "Surest Health Plan",
    "Sutter Health Aetna",
    "Sutter Health Plus",
    "Sutter SElect",
    "Tenndent",
    "Texas Children’s Health Plan",
    "Texas Health Aetna",
    "The Health Plan Of West Virginia",
    "The Ullico Family Of Companies",
    "Thrivent",
    "Today’s Option (American Progressive And Pyramid Life)",
    "Transactrx Infusion And Specialty",
    "Transactrx PArt D",
    "Transamerica Admin By Kba",
    "Transamerica Life Insurance Company",
    "Tribute Health Plan",
    "Tricare East",
    "Tricare For Life",
    "Tricare Overseas",
    "Tricare West",
    "Trillium Community Health Plan",
    "Triple S Advantage",
    "Truli Health",
    "Trustmark Insurance",
    "Tufts Health Plan",
    "Ucare Of Minnesota",
    "Ultimate Health Plans",
    "Umr (Wausau)",
    "Umr - Wausau/Uhis (Teladoc Only)",
    "Umwa Health And Retirement Funds",
    "Underwriters Safety And Claims",
    "Unicare (Wellpoint)",
    "Unicare Dental",
    "Unified Group SErvices - (Web Credentials Required)",
    "Union PAcific Railroad Employees Health Systems",
    "United American Insurance Co",
    "United Concordia Companies, Inc. - Dental",
    "United Concordia Federal Employees Program - Dental",
    "United Insurance Company Of America (Kemper)",
    "United States Fire Insurance Company",
    "United Teacher Assoc Insurance Company - Medicare Supplement",
    "Unitedhealthcare - Care Improvement Plus",
    "Unitedhealthcare - Definity Health",
    "Unitedhealthcare - Mamsi Health Plan",
    "Unitedhealthcare - Uhcwest (Pacificare)",
    "Unitedhealthcare - Wea",
    "Unitedhealthcare Community Plan (Oh, PA, Sc) (Three Rivers Health Plans)",
    "Unitedhealthcare Community Plan - Kansas",
    "Unitedhealthcare Community Plan-Tennessee",
    "Unitedhealthcare Dental",
    "Unitedhealthcare Facets Detroit - Community And State",
    "Unitedhealthcare NEvada Market",
    "Unitedhealthcare Of Oklahoma",
    "Unitedhealthcare River Valley",
    "Unitedhealthcare SEcure Horizons",
    "Unitedhealthcare Student Resources",
    "Unitedhealthcare",
    "Unity Health Plans",
    "Univera",
    "Universal American",
    "University Family Care",
    "University Health Alliance (Web Credentials Required)",
    "University Of Arizona Health Plans",
    "University Of Utah Health Plans",
    "University Physicians Care Advantage (Arizona)",
    "Upmc Health Plan (Tristate)",
    "Usaa Life Insurance Company",
    "Usaa Medicare Supplemental",
    "Va Fee Basis Program",
    "Va Health Administration Center",
    "Va Healthcare",
    "Va",
    "Valley Care Program",
    "Valley Health Plan",
    "Vantage Health Plan, Inc.",
    "Vibra Health Plan",
    "Virginia Surety Company, Inc",
    "Viva Health",
    "Vns Choice",
    "Washington National",
    "Wea Trust",
    "Web-Tpa, Inc.",
    "Wellcare Health Plans",
    "Wellsense",
    "Western & Southern Financial Group",
    "Western Health Advantage",
    "Western Sky Community Care",
    "Wilson Mcshane - Dental",
    "Windsor Medicare Extra",
    "Wps Health Insurance",
    "Youthcare Healthcare Illinois",
    "Zing Health"
];