

export const CompanyNames = [
    "1199 National Benefit Fund",
    "AARP",
    "Acclaim Inc.",
    "Ace Property and Casualty Insurance Company",
    "ACS Benefit Services, Inc.",
    "Administrative Services, Inc.",
    "Advantage by Bridgeway Health Solutions",
    "Advantage by Buckeye Community Health Plan",
    "Advantage by Managed Health Services",
    "Advantage by Superior HealthPlan",
    "Aetna (Commercial Plans Only)",
    "Aetna Better Health (CA)",
    "Aetna Better Health (FL)",
    "Aetna Better Health (IL)",
    "Aetna Better Health (KS)",
    "Aetna Better Health (KY)",
    "Aetna Better Health (LA)",
    "Aetna Better Health (MD)",
    "Aetna Better Health (MI)",
    "Aetna Better Health (NJ)",
    "Aetna Better Health (NV)",
    "Aetna Better Health (OH)",
    "Aetna Better Health (PA)",
    "Aetna Better Health (TX)",
    "Aetna Better Health (TX) CHIP",
    "Aetna Better Health (VA)",
    "Aetna Better Health (WV)",
    "Aetna Long Term Care",
    "Aetna OhioRise - Ohio Medicaid MCE",
    "Aetna Retiree Medical Plan Administrator",
    "Aetna Senior Supplemental",
    "AFLAC",
    "AFLAC - Dental",
    "AFLAC - Medicare Supplemental",
    "AgeWell New York (Web Credentials Required)",
    "AGIA, Inc.",
    "Alameda Alliance for Health Plan (Web Credentials Required)",
    "Alan Sturm and Associates - Dental",
    "Albuquerque Public Schools",
    "Aliera Health Care",
    "All Savers Life Insurance",
    "Allegiance Benefit Plan Management Inc.",
    "Alliance Coal Health Plan",
    "Alliant Health Plans",
    "Allianz Life Insurance Company of New York",
    "Allied Benefit Systems, Inc.",
    "Allina Health Aetna",
    "Allwell",
    "AlohaCare",
    "Alternative Insurance Resources, Inc",
    "Altius Health Plans",
    "Altus Dental",
    "Ambetter",
    "Ambetter New Hampshire Healthy Families",
    "Ambetter of Arkansas",
    "Ambetter of Illinois",
    "Ambetter of Tennessee",
    "Ambetter Superior Health Plan (TX)",
    "AmeriBen",
    "American Family Insurance Group",
    "American General Life and Accident",
    "American General Life Insurance Company",
    "American Health Advantage of Florida",
    "American Health Advantage of Mississippi",
    "American Health Advantage of Missouri",
    "American Health Advantage of Oklahoma",
    "American Health Advantage of Tennessee",
    "American Health Advantage of TX",
    "American Health Advantage of Utah",
    "American Healthcare Alliance",
    "American Income Life Insurance Company",
    "American Insurance Administrators",
    "American Medical Security (AMS)",
    "American National Insurance",
    "American National Life Insurance Company of Texas",
    "American Network Insurance Medicare Supplement",
    "American Postal Workers Union (APWU)",
    "American Republic Insurance Company (ARIC)",
    "American Retirement Life Insurance Company - Medicare Supplement",
    "Americhoice - Community and State",
    "AmeriChoice of New Jersey (Commercial)",
    "AmeriChoice of New Jersey (Medicaid)",
    "Americo Financial Life & Annuity",
    "Amerigroup",
    "Amerihealth (DE, NJ, PA) - Inst Submitters",
    "Amerihealth (DE,NJ,PA) - Professional Submitters Only",
    "AmeriHealth Administrators",
    "Amerihealth Caritas DC",
    "AmeriHealth Caritas Delaware",
    "Amerihealth Caritas Florida",
    "AmeriHealth Caritas Louisiana (formerly LaCare)",
    "AmeriHealth Caritas New Hampshire",
    "AmeriHealth Caritas Next NC",
    "AmeriHealth Caritas North Carolina",
    "Amerihealth Caritas Northwestern PA",
    "Amerihealth Caritas Ohio Medicaid MCE",
    "AmeriHealth Caritas Pennsylvania",
    "AmeriHealth Caritas VIP Care Plus",
    "AmeriHealth New Jersey",
    "AmeriHealth Northeast Pennsylvania",
    "AmeriHealth Pennsylvania",
    "AmeriHealth VIP Care",
    "Ameritas Group - Ameritas Life Insurance Company",
    "Ameritas Group - First Ameritas of New York",
    "Ameritas Group - First Reliance Standard Life",
    "Ameritas Group - Reliance Standard Life",
    "Ameritas Group - Standard Insurance",
    "Ameritas Group - Standard Insurance of New York",
    "Anthem BC California Dental",
    "Anthem BCBS - OHIO MEDICAID MCE",
    "Anthem BCBS Colorado Dental",
    "Anthem BCBS Connecticut Dental",
    "Anthem BCBS GA Dental",
    "Anthem BCBS Indiana Dental",
    "Anthem BCBS Kentucky Dental",
    "Anthem BCBS Maine Dental",
    "Anthem BCBS Missouri Dental",
    "Anthem BCBS Nevada Dental",
    "Anthem BCBS New Hampshire Dental",
    "Anthem BCBS Ohio Dental",
    "Anthem BCBS Virginia Dental",
    "Anthem BCBS Wisconsin Dental",
    "Anthem Health Keepers",
    "Anthem Vivity",
    "Arise Health Care",
    "Arise Health Plan Medicare Select Policy",
    "Arizona Complete Care",
    "Arizona Physicians IPA - Community and State",
    "Arkansas Total Care",
    "ArmadaCare",
    "Arnett Health Plan",
    "Aspire Health Plan",
    "Aspirus Medicare Advantage",
    "Asuris Northwest Health",
    "Atrio Health Plan",
    "Aultcare",
    "Automated Benefit Services",
    "Auxiant",
    "Avera Health Plans",
    "AvMed Health Plans",
    "BadgerCare Plus",
    "Bankers Fidelity Life Insurance Company",
    "Bankers Life and Casualty",
    "Banner Aetna",
    "Banner University Family Care",
    "Baycare Select Health Plans",
    "BC Illinois Medicare Advantage",
    "BC Montana Medicare Advantage",
    "BC New Mexico Medicare Advantage",
    "BC Oklahoma Medicare Advantage",
    "BC Texas Medicare Advantage",
    "BCBS HI - Hawaii Medical Service Association HMSA",
    "BCBS LA Medicare Advantage",
    "BCBS of Arizona Advantage",
    "BCBS Texas Medicaid Star CHIP",
    "BCBS Texas Medicaid Star Kids",
    "BCBS Western New York Medicaid",
    "BCBSMN Blue Plus Medicaid",
    "BCBSMN Blue Plus Medicaid Non - Emergency Transport",
    "Behavioral Health Systems, Inc",
    "BeneBay",
    "Benefit Management Inc.",
    "Better Health Plans (Unison Health Plan)",
    "Better Health Plans of Florida",
    "BIND",
    "Blue Advantage - BCBS LA",
    "Blue Benefit Administrators of Mass",
    "Blue Cross Blue Shield Alabama - Institutional (BCBS AL)",
    "Blue Cross Blue Shield Alabama - Professional (BCBS AL)",
    "Blue Cross Blue Shield Arizona (BCBS AZ)",
    "Blue Cross Blue Shield Arkansas (BCBS AR)",
    "Blue Cross Blue Shield Colorado - Anthem (BCBS CO)",
    "Blue Cross Blue Shield Connecticut - Anthem (BCBS CT)",
    "Blue Cross Blue Shield DE (Highmark) - Prof & Inst Claim Submitters only",
    "Blue Cross Blue Shield DE (Highmark) - Prof Claim Submitters only",
    "Blue Cross Blue Shield Dist. of Columbia - CareFirst (BCBS DC)",
    "Blue Cross Blue Shield Florida (BCBS FL)",
    "Blue Cross Blue Shield Georgia - Anthem (BCBS GA)",
    "Blue Cross Blue Shield Illinois - HCSC (BCBS IL)",
    "Blue Cross Blue Shield Indiana - Anthem (BCBS IN)",
    "Blue Cross Blue Shield Iowa (BCBS IA)",
    "Blue Cross Blue Shield Kansas (BCBS KS)",
    "Blue Cross Blue Shield Kansas City (BCBS KS)",
    "Blue Cross Blue Shield Kentucky - Anthem (BCBS KY)",
    "Blue Cross Blue Shield Louisiana (BCBS LA)",
    "Blue Cross Blue Shield Maine - Anthem (BCBS ME)",
    "Blue Cross Blue Shield Maryland - CareFirst (BCBS MD)",
    "Blue Cross Blue Shield Massachusetts (BCBS MA)",
    "Blue Cross Blue Shield Michigan - Institutional (BCBS MI)",
    "Blue Cross Blue Shield Michigan - Professional (BCBS MI)",
    "Blue Cross Blue Shield Minnesota (BCBS MN)",
    "Blue Cross Blue Shield Mississippi (BCBS MS)",
    "Blue Cross Blue Shield Missouri - Anthem (BCBS MO)",
    "Blue Cross Blue Shield Montana - HCSC (BCBS MT)",
    "Blue Cross Blue Shield Nebraska (BCBS NE)",
    "Blue Cross Blue Shield Nevada - Anthem (BCBS NV)",
    "Blue Cross Blue Shield New Hampshire - Anthem (BCBS NH)",
    "Blue Cross Blue Shield New Jersey - Horizon (BCBS NJ)",
    "Blue Cross Blue Shield New Mexico - HCSC (BCBS NM)",
    "Blue Cross Blue Shield New York - Central (BCBS NY)",
    "Blue Cross Blue Shield New York - Empire Anthem (BCBS NY)",
    "Blue Cross Blue Shield New York - Excellus (BCBS NY)",
    "Blue Cross Blue Shield New York - Rochester (BCBS NY)",
    "Blue Cross Blue Shield New York - Utica (BCBS NY)",
    "Blue Cross Blue Shield North Carolina (BCBS NC)",
    "Blue Cross Blue Shield North Dakota (BCBS ND)",
    "Blue Cross Blue Shield Ohio - Anthem (BCBS OH)",
    "Blue Cross Blue Shield Oklahoma - HCSC (BCBS OK)",
    "Blue Cross Blue Shield Oregon - Regence (BCBS OR)",
    "Blue Cross Blue Shield PA - Highmark Inst Claim Submitter Only",
    "Blue Cross Blue Shield PA - Highmark INSTITUTIONAL ONLY",
    "Blue Cross Blue Shield PA - Highmark PROFESSIONAL",
    "Blue Cross Blue Shield Pennsylvania - Northeastern (BCBS PA)",
    "Blue Cross Blue Shield Puerto Rico - Triple-S Salud (BCBS PR)",
    "Blue Cross Blue Shield Rhode Island (BCBS RI)",
    "Blue Cross Blue Shield South Carolina (BCBS SC)",
    "Blue Cross Blue Shield South Dakota (BCBS SD)",
    "Blue Cross Blue Shield Tennessee (BCBS TN)",
    "Blue Cross Blue Shield Texas - HCSC (BCBS TX)",
    "Blue Cross Blue Shield Utah - Regence (BCBS UT)",
    "Blue Cross Blue Shield Vermont (BCBS VT)",
    "Blue Cross Blue Shield Virginia - Anthem (BCBS VA)",
    "Blue Cross Blue Shield Western New York - (BCBSWNY)",
    "Blue Cross Blue Shield Wisconsin - Anthem (BCBS WI)",
    "Blue Cross Blue Shield WV - Highmark INSTITUTIONAL",
    "Blue Cross Blue Shield WV - Highmark PROFESSIONAL",
    "Blue Cross Blue Shield Wyoming (BCBS WY)",
    "Blue Cross California - Anthem (BC CA)",
    "Blue Cross Community Centennial",
    "Blue Cross Community Options",
    "Blue Cross Idaho (BC ID)",
    "Blue Cross Pennsylvania - Capital (BCBS PA)",
    "Blue Cross Pennsylvania - Independence - INST",
    "Blue Cross Pennsylvania - Independence - Professional",
    "Blue Cross Washington and Alaska - Premera (BCWA, BC AK)",
    "Blue Medicare Advantage",
    "Blue Shield California (BS CA)",
    "Blue Shield Idaho - Regence (BS ID)",
    "Blue Shield New York - Northeastern (BS NY)",
    "Blue Shield Washington - Regence (BS WA)",
    "BlueChoice HealthPlan South Carolina Medicaid",
    "BlueCross Medicare Advantage",
    "BMC HealthNet Plan",
    "Boon Group",
    "Boon-Chapman Benefit Admin",
    "Braven Health",
    "Bravo Health",
    "Bridgespan",
    "Bright Health Plan Medicare Advantage - DOS 1/1/2022 and After",
    "Bright Health Plan Medicare Advantage DOS 12/31/2021 and Before",
    "Bright Healthcare - DOS 1/1/2022 and After",
    "Bright Healthcare - DOS 12/31/2021 and Before",
    "Brokers National-Dental",
    "Cal-Viva",
    "California Children Services (Web Credentials Required)",
    "CalOptima",
    "Capital Administrators",
    "Capital District Physicians Health Plan (CDPHP)",
    "Capital Health Plan",
    "Caprock",
    "Care N’ Care",
    "Care1st Health Plan Arizona",
    "Care1st of California (Web Credentials Required)",
    "CareFirst Administrators",
    "Carefirst Medicare Advantage",
    "Carelon Behavioral Health",
    "CareMore",
    "CarePartners of Connecticut",
    "CarePlus Health Plan",
    "CareSource Arkansas",
    "Caresource Georgia",
    "Caresource Health",
    "Caresource Indiana",
    "Caresource Michigan Medicaid",
    "Caresource North Carolina",
    "Caresource Ohio",
    "CareSource OHIO MEDICAID MCE",
    "Caresource West Virginia",
    "Carolina Care Plan, Inc. (CCP)",
    "Carolina Complete Health",
    "Carpenters Health and Welfare Trust Fund of St Louis",
    "CDS Group Health",
    "Celtic Insurance",
    "CenCal",
    "Cenpatico - Arizona",
    "Cenpatico - Florida",
    "Cenpatico - Georgia",
    "Cenpatico - Illinois",
    "Cenpatico - Indiana",
    "Cenpatico - Kansas",
    "Cenpatico - Kentucky",
    "Cenpatico - Massachusetts",
    "Cenpatico - Mississippi",
    "Cenpatico - Missouri",
    "Cenpatico - New Hampshire",
    "Cenpatico - Ohio",
    "Cenpatico - South Carolina",
    "Cenpatico - Texas",
    "Cenpatico - Wisconsin",
    "Cenpatico Behavioral Health",
    "Cenpatico Behavioral Health Texas",
    "Centene - Absolute Total Care",
    "Centene - Advantage by Peach State",
    "Centene - Advantage by Sunshine State",
    "Centene - Ambetter Sunshine Health",
    "Centene - Ascension Complete",
    "Centene - Bridgeway Arizona",
    "Centene - Buckeye Community Health",
    "Centene - California Health and Wellness",
    "Centene - Celticare",
    "Centene - Granite State Health Plan",
    "Centene - Home State Health Plan",
    "Centene - Kentucky Spirit Health Plan",
    "Centene - Louisiana Healthcare Connections",
    "Centene - Managed Health Services Indiana",
    "Centene - Managed Health Services Wisconsin",
    "Centene - Michigan Fidelis Secure Care",
    "Centene - New Hampshire Healthy Families",
    "Centene - OHIO MEDICAID MCE",
    "Centene - Peach State Health Plan",
    "Centene - Sunflower State Health (Kansas)",
    "Centene - Sunshine State Health Plan",
    "Centene - Superior HealthPlan Texas",
    "Centene - Total Care Carolina",
    "Centene Advantage Plans",
    "Centivo",
    "Central CA Alliance for Health",
    "Central Health Medicare Plan (Web Credentials Required)",
    "Central Reserve Life Ins Co. Medicare Supplement",
    "Central States Fund",
    "Central States Health & Life Co. of Omaha",
    "Central States Indemnity",
    "Cerner Health Plan",
    "CHAMPVA/Spina Bifida/Children of Women Vietnam Vets",
    "Children’s Mercy PCN",
    "Christian Brothers Services",
    "Christie Student Health Plans",
    "CHRISTUS Health Plan Medicaid",
    "CHRISTUS Health Plan NM Medicare Advantage",
    "Christus Health Plan TX HIX",
    "Cigna",
    "Claims Management Service Inc.",
    "Clear Health Alliance",
    "Clover Health",
    "CMFG Life Insurance",
    "Coastal Management Services-Aspire (Web Credentials Required)",
    "Colonial Penn Life",
    "Colorado Access",
    "Colorado Community Health Alliance",
    "Common Ground",
    "Commonwealth Care Alliance (CCA)",
    "Community Care of Oklahoma",
    "Community Health Choice",
    "Community Health Group (CHG)",
    "Community Health Plan",
    "Community Health Plan of Washington (CHPW)",
    "Community Healthfirst Medicare Advantage",
    "Concentrix Insurance Solutions",
    "ConnectiCare",
    "Connecticare - Medicare",
    "Consolidated Associates Railroad",
    "Consolidated Health Plan (Web Credentials Required)",
    "Constellation Health",
    "Consumers Life",
    "Consumers Mutual Insurance of Michigan",
    "Continental General Insurance Company - Medicare Supplement",
    "Continental Life Insurance Company of Brentwood, Tennessee",
    "Cook Childrens Health Plan",
    "Cook Medical Group",
    "Cooperative Benefit Administrators (CBA)",
    "Coordinated Care",
    "CoreSource (FMH)",
    "CoreSource (Little Rock)",
    "CoreSource (MD, PA, IL, NC,IN, AZ, MN)",
    "CoreSource (Ohio)",
    "Country Life Insurance Company",
    "CountyCare",
    "Covenant Administrators (TPA)",
    "Coventry Health Care of Florida",
    "Cox Health Plan",
    "Crum & Forster",
    "CSI Life Insurance Company",
    "Culinary Health Fund UNITE HERE HEALTH",
    "Dean Health Plan",
    "DeCare Dental Health Insurance",
    "Delta Dental Insurance Company - Alabama",
    "Delta Dental Insurance Company - Florida",
    "Delta Dental Insurance Company - Georgia",
    "Delta Dental Insurance Company - Louisiana",
    "Delta Dental Insurance Company - Mississippi",
    "Delta Dental Insurance Company - Montana",
    "Delta Dental Insurance Company - Nevada",
    "Delta Dental Insurance Company - Oklahoma",
    "Delta Dental Insurance Company - Texas",
    "Delta Dental Insurance Company - Utah",
    "Delta Dental of Arizona",
    "Delta Dental of California",
    "Delta Dental of Colorado",
    "Delta Dental of Connecticut",
    "Delta Dental of Delaware",
    "Delta Dental of Hawaii",
    "Delta Dental of Illinois",
    "Delta Dental of Iowa",
    "Delta Dental of Maryland",
    "Delta Dental of Michigan",
    "Delta Dental of Minnesota",
    "Delta Dental of Missouri",
    "Delta Dental of Nebraska",
    "Delta Dental of New Jersey",
    "Delta Dental of New York",
    "Delta Dental of North Dakota",
    "Delta Dental of Pennsylvania",
    "Delta Dental of Rhode Island",
    "Delta Dental of Virginia",
    "Delta Dental of Washington DC",
    "Delta Dental of Washington State",
    "Delta Dental of West Virginia",
    "DeltaCare USA - Claims",
    "DeltaCare USA - Encounters",
    "Dental Benefit Providers",
    "DentaQuest",
    "Denver Health Medical Plan",
    "Deseret Mutual (DMBA)",
    "Devoted Health",
    "Director’s Guild",
    "District No. 9, I. A. of M. & A. W. Welfare Trust",
    "Diversified Administration Corp",
    "Doctors Healthcare Plans",
    "Driscoll Health Plan",
    "Easy Choice Health Plan California",
    "EBMS (Employee Benefit Management Services, Inc.)",
    "Educators Mutual Insurance (EMI)",
    "Elderplan",
    "Elips Life Insurance Company",
    "Emblem Health (GHI HMO, GHI PPO, HIP, Vytra)",
    "Empire BC New York Dental",
    "Employee Benefit Services - Dental",
    "Empower Arkansas",
    "Entrust",
    "EPSI, Inc.",
    "Erie Family Life Insurance Company",
    "Essence Healthcare",
    "Evercare",
    "Everence Financial",
    "Everest Reinsurance Company",
    "Evergreen Health",
    "Evergreen Health Co-Op",
    "Everpointe",
    "Evry Health",
    "Exclusicare",
    "Fallon Community Health Plan",
    "Farm Bureau Health Plans",
    "Federated Insurance",
    "Fidelis Care New York",
    "First Carolina Care",
    "First Choice Health Network",
    "First Choice VIP Care Plus",
    "First Medical Network",
    "First United American Insurance Company",
    "FirstCare",
    "Fiserv Wausau",
    "Flex Compensation - Dental",
    "Florida Blue Medicare",
    "Florida Combined Life - DENTAL",
    "Florida Health Care Plans",
    "Food Employers & Bakery",
    "Freedom Health Medicare Advantage",
    "Friday Health Plan",
    "FSL Admin by KBA",
    "G.M.P. Employers Retiree Trust",
    "Gateway Health Plan",
    "GEHA - Government Employees Hospital Association",
    "Geisinger Health Plan",
    "Geisinger Health Plan Gold",
    "GEMCare",
    "Genworth Life and Annuity Insurance",
    "Genworth Life Insurance Company",
    "Gilsbar",
    "Global Health Inc",
    "Globe Life & Accident Insurance Company",
    "Gold Coast Health Plan (Web Credentials Required)",
    "Gold Kidney Health Plan",
    "Golden Rule",
    "Golden West Dental",
    "Great American Life Insurance Company Medicare Supplement",
    "Great Southern Life Insurance Company",
    "Group and Pension Administrators",
    "Group Dental Service",
    "Group Health Northwest",
    "Group Hospitalization and Medical Services",
    "Group Practice Affiliates",
    "Guardian Life Insurance Company of America - Dental",
    "Harmony Health Plan",
    "Harvard Pilgrim Health Care",
    "Hawaii Mainland Admin (HMA)",
    "Hawaii Medical Assurance Association",
    "Health Alliance Medical Plan (IL)",
    "Health Alliance Medical Plans (HAP)",
    "Health Choice Arizona",
    "Health Choice Oklahoma",
    "Health First Health Plan",
    "Health First Insurance",
    "Health Net National",
    "Health New England",
    "Health Partners Pennsylvania",
    "Health Plan of San Mateo",
    "Health Plan of Upper Ohio Valley",
    "Health Services for Children with Special Needs",
    "Health Share of Oregon (Care Oregon)",
    "Health Tradition",
    "Healthcare Highways",
    "Healthcare Management Administrators",
    "HealthChoice Select",
    "HealthComp Administrators",
    "HEALTHe Exchange",
    "HealthEase",
    "HealthEase Kids",
    "Healthfirst New York",
    "Healthfirst of New Jersey",
    "Healthgram (Primary PhysiciansCare)",
    "HealthNow",
    "HealthPartners MN",
    "HealthPlan of Nevada",
    "HealthPlans Inc.",
    "HealthPlus of Michigan",
    "HealthScope (Morris Assoc, Central Benefits, Employers Health, Plan Handlers)",
    "HealthScope Benefits Inc.",
    "HealthScope HSB",
    "HealthSmart Benefit Solutions",
    "HealthSmart Benefit Solutions (Wells Fargo TPA)",
    "Healthsource Provident - Dental",
    "HealthSpring",
    "Healthteam Advantage",
    "Healthy Blue Dual Advantage Louisiana",
    "Healthy Blue Louisiana",
    "Healthy Blue Missouri",
    "Healthy Blue Nebraska",
    "Healthy Blue North Carolina",
    "Healthy Blue South Carolina",
    "Hennepin Health - Metropolitan Health Plan (MHP)",
    "Hershey Healthsmile - Dental",
    "Highmark Senior Solutions Company",
    "HIPNY",
    "HM Care Advantage Admin by KBA",
    "Hometown Health",
    "Hooray Health",
    "Horizon New Jersey Health",
    "HSBS Oklahoma City",
    "Hudson Health Plan",
    "Humana",
    "Humana - Health Horizons (OHIO MEDICAID MCE)",
    "Humana CareSource (KY)",
    "Humana Long Term Care",
    "iCare (Independent Care Health Plan)",
    "IlliniCare Health Plan",
    "Independence Administrators",
    "Independent Health",
    "Indiana University Health Plan (Medicare)",
    "Indiana University Health Plans (Commercial)",
    "Inland Empire Health",
    "Innovation Health",
    "Insurers Administrative Corporation (IAC)",
    "Integra Administrative Group",
    "Integrated Mental Health Services",
    "Iowa Total Care",
    "Jai Medical Systems",
    "Johns Hopkins Advantage MD",
    "Johns Hopkins Employee Health Plan",
    "Johns Hopkins Health Plan",
    "Johns Hopkins HealthCare LLC",
    "Johns Hopkins US Family Health Plan",
    "Kaiser Foundation Health Plan of Colorado",
    "Kaiser Foundation Health Plan of Hawaii",
    "Kaiser Foundation Health Plan of The Mid-Atlantic",
    "Kaiser Foundation Health Plan of The Northwest",
    "Kaiser Foundation Health Plan of Washington",
    "Kaiser Foundation Ohio",
    "Kaiser Permanente KPIC",
    "Kaiser Permanente of Georgia",
    "Kaiser Permanente of Northern CA",
    "Kaiser Permanente of Southern CA",
    "Kelsey-Seybold",
    "Kemper Benefits",
    "Kentucky Passport (formerly Passport Health Plan)",
    "Key Benefit Administrators",
    "Key Benefit Administrators (IN)",
    "Key Healthy Partners",
    "KeySolution",
    "Keystone First Community Health Plan",
    "Keystone Mercy Health",
    "Keystone VIP Care",
    "Kitsap Physician Services",
    "KSKJ Life",
    "L.A. Care Health Plan",
    "Lasso Healthcare MSA",
    "Leon Medical Centers Health Plan",
    "Liberty National Life Insurance Company",
    "LifeCare Assurance Company",
    "Lifewise Arizona",
    "Lifewise Assurance Company",
    "Lifewise Plan of Oregon",
    "Lifewise Plan of Washington",
    "Lighthouse Health Plan",
    "Lincoln Financial",
    "Lincoln Heritage",
    "Local 1199",
    "LoneStar TPA",
    "Loomis Company",
    "Louisiana Health Exchange",
    "Loyal American Life Insurance Company - Medicare Supplement",
    "Loyal Christian Benefit Association",
    "Lucent Health",
    "Lumico Life Insurance",
    "Magellan Behavioral Health",
    "Magellan Complete Care of Virginia",
    "Magellan Health Care",
    "MagnaCare",
    "Magnolia Health Plan",
    "Maine Community Health Options",
    "Managed Care of America",
    "Managed Care of North America",
    "Managed Care Systems - (Web Credentials Required)",
    "Managed Health Network (MHN)",
    "MAPFRE Life Puerto Rico",
    "March Vision Care",
    "Maricopa Care Advantage (Arizona)",
    "Martins Point Health Care",
    "Mary Washington Medicare Advantage",
    "Maryland Physicians Care",
    "Mass General Brigham Health Plan (FKA: Allways Health Partners)",
    "McLaren Health Care",
    "MDWise Medicaid Health Plans",
    "Med-Pay Inc",
    "MedBen",
    "MedCost Benefit Services",
    "Medica",
    "Medica Government Programs",
    "Medica Health Care Plan - Florida",
    "Medica Health Plan Solutions",
    "Medica Health Plans (Medicare Advantage LOB)",
    "Medica2 - Group/Policy is: IFB Individual Family Benefits",
    "Medicaid Alabama (AL)",
    "Medicaid Alaska (AK)",
    "Medicaid Arizona - AHCCCS (AZ)",
    "Medicaid Arkansas (AR)",
    "Medicaid California - Medi-Cal (CA)",
    "Medicaid Colorado (CO)",
    "Medicaid Connecticut (CT)",
    "Medicaid Delaware (DE)",
    "Medicaid District of Columbia (DC)",
    "Medicaid Florida (FL)",
    "Medicaid Georgia (GA)",
    "Medicaid Hawaii (HI)",
    "Medicaid Idaho (ID)",
    "Medicaid Illinois (IL)",
    "Medicaid Indiana (IN)",
    "Medicaid Iowa (IA)",
    "Medicaid Kansas (KS)",
    "Medicaid Kentucky (KY)",
    "Medicaid Louisiana (LA)",
    "Medicaid Maine (ME)",
    "Medicaid Maryland (MD)",
    "Medicaid Massachusetts (MA)",
    "Medicaid Michigan - Michigan MIChild (MI)",
    "Medicaid Michigan (MI)",
    "Medicaid Michigan (MI) Pending Eligibility",
    "Medicaid Minnesota (MN)",
    "Medicaid Mississippi - CHIP (MS)",
    "Medicaid Mississippi (MS)",
    "Medicaid Missouri (MO)",
    "Medicaid Montana (MT)",
    "Medicaid Nebraska (NE)",
    "Medicaid Nevada (NV)",
    "Medicaid New Hampshire (NH)",
    "Medicaid New Jersey (NJ)",
    "Medicaid New Mexico (NM)",
    "Medicaid New York (NY)",
    "Medicaid North Carolina (NC)",
    "Medicaid North Dakota (ND)",
    "Medicaid Ohio (OH)",
    "Medicaid Oklahoma (OK)",
    "Medicaid Oregon (OR)",
    "Medicaid Pennsylvania (PA)",
    "Medicaid Rhode Island (RI) (Web Credentials Required)",
    "Medicaid South Carolina (SC)"
]